# Setup
title:        Haskell Labs
tagline:      Declarative Programming Labs Supplement
baseurl:      ""
permalink:    :title

# About/contact
author:
  name:       Stefan Niculae
  email:      stefan1niculae@github.com
  github:     stefan1niculae

# Gems
gems:
  # - jekyll-paginate

# Others
markdown: kramdown
highlighter: rouge
# kramdown:
  # input: GFM
  # syntax_highlighter: rouge

future: false
